### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'172.22.0.1' (using password: YES)

### ISSUE THREAD

**Issue by brivadeneira** [zhenghaoz/gorse#308]
**Gorse version**
lastest from docker image

**Describe the bug**
`ERROR 1045 (28000): Access denied for user 'root'@'172.22.0.1' (using password: YES)` is showed when trying to import github data as: `mysql -h 127.0.0.1 -u root -proot_pass gorse < github.sql`

**To Reproduce**

```sh
~/gorse $ nano docker-compose.yml
```

```yml
version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  mysql:
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
  worker:
    image: zhenghaoz/gorse-worker
    restart: unless-stopped
    ports:
      - 8089:8089
    command: >
      --master-host master --master-port 8086 --http-host 0.0.0.0 --http-port 8089
      --log-path /var/log/gorse/worker.log --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - ./var/log/gorse:/var/log/gorse
      - ./var/lib/gorse:/var/lib/gorse
  server:
    image: zhenghaoz/gorse-server
    restart: unless-stopped
    ports:
      - 8087:8087
    command: >
      --master-host master --master-port 8086 --http-host 0.0.0.0 --http-port 8087
      --log-path /var/log/gorse/server.log --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - ./var/log/gorse:/var/log/gorse
      - ./var/lib/gorse:/var/lib/gorse
  master:
    image: zhenghaoz/gorse-master
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8088:8088
    command: -c /etc/gorse/config.toml --log-path /var/log/gorse/master.log --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./config.toml:/etc/gorse/config.toml
      - ./var/log/gorse:/var/log/gorse
      - ./var/lib/gorse:/var/lib/gorse
```

```sh
~/gorse $ docker-compose up -d
```

```sh
~/gorse $ wget https://cdn.gorse.io/example/github.sql
~/gorse $ mysql -h 127.0.0.1 -u root -proot_pass gorse < github.sql
```

**Expected behavior**
Import data successfully 

**Additional context**
* I have tried with root user
* I have tried with config.toml file, but during the docker building, it expects a directory instead of a file
