### ISSUE TITLE
Rest API Recommends Not Found

### ISSUE THREAD

**Issue by mehmetcansahin** [zhenghaoz/gorse#36]
Hello, when I add dummy data and then list the recommends, I get an error like "3 not found". But when I list users, I see 3 id 
users in the list. I can see the feedback of 3 id users. So why am I getting such an error even though there are 3 id users? 

[gorse.db.zip](https://github.com/zhenghaoz/gorse/files/4947541/gorse.db.zip)

config.toml
```toml
# This section declares settings for the server.
[server]
host = "127.0.0.1"      # server host
port = 8888             # server port

# This section declares setting for the database.
[database]
file = "gorse.db"       # database file

# This section declares settings for recommendation.
[recommend]
model = "bpr"           # recommendation model
cache_size = 100        # the number of cached recommendations
update_threshold = 10   # update model when more than 10 ratings are added
check_period = 1        # check for update every one minute
similarity = "pearson"  # similarity metric for neighbors
fit_jobs = 1            # concurrent jobs for fitting

# This section declares hyperparameters for the recommendation model.
[params]
n_factors = 10          # the number of latent factors
reg = 0.01              # regularization strength
lr = 0.05               # learning rate
n_epochs = 100          # the number of learning epochs
init_mean = 0.0         # the mean of initial latent factors initilaized by Gaussian distribution
init_std = 0.001        # the standard deviation of initial latent factors initilaized by Gaussian distribution
```
